version: "3.9"
services:
  SHO_Task.api:
    image: ${DOCKER_REGISTRY-}potaskapi
    container_name: SHO_Task.Api
    build:
      context: .
      dockerfile: SHO_Task.Api/Dockerfile
    ports:
      - "7199:7199"
    environment:
      - ASPNETCORE_URLS=http://+:7199
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sho-db;Database=SHO_TaskDB;User Id=sa;Password=admin@123;TrustServerCertificate=True;
    depends_on:
      - sho-db
    networks:
      - appnetwork

  sho-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sho-db
    ports:
      - "1435:1433" # Map SQL Server port to host
    environment:
      SA_PASSWORD: "admin@123"
      ACCEPT_EULA: "Y"
    networks:
      - appnetwork
    volumes:
      - shosqlserverdata:/var/opt/mssql

networks:
  appnetwork:

volumes:
  shosqlserverdata:
